/**
 * English content.
 * Edit text here manually to change the site copy.
 */
export const en = {
    nav: {
        home: "Home",
        about: "About",
        education: "Education",
        skills: "Skills",
        project1: "Project 1",
        project2: "Project 2",
        project3: "Project 3",
        achievements: "Achievements",
        challenges: "Challenges",
        career: "Career",
        contact: "Contact",
        portfolio: "Portfolio",
    },

    opening: {
        badge: "IDN Boarding School · Software Engineer",
        greeting: "Hello, I'm",
        nameLine1: "Jose Shabra",
        nameLine2: "Shatilla Rajjawani",
        chip1: "Full Stack Developer",
        chip2: "Web Engineer",
        bio: "Building **clean**, **responsive**, and **modern** web experiences — empowering local businesses to grow online.",
        mission: "This portfolio introduces my skills, experience, and career goals as a software engineer.",
        ctaBegin: "Let's Begin",
        ctaProjects: "View Projects",
        available: "Available for Projects",
        roleTop: "Full Stack",
        roleBot: "Developer",
        scrollHint: "Scroll to explore",
    },

    about: {
        tag: "Get to know me",
        title: "About Me",
        subtitle: "A passionate developer who believes in building meaningful things through clean code and creative thinking.",
        backgroundTitle: "Background",
        backgroundBody: "I'm **Jose Shabra Shatilla Rajjawani**, a student at **IDN Boarding School, Solo**, majoring in **Software Engineering (RPL)**. I have a deep passion for technology and software development — constantly exploring new tools, building projects, and pushing the boundaries of what I can create.",
        strengthsTitle: "Personal Strengths",
        strengths: [
            { label: "Adaptability", desc: "Thrive in fast-changing environments" },
            { label: "Time Management", desc: "Deliver work on time, every time" },
            { label: "Target Oriented", desc: "Stay focused until the goal is reached" },
        ],
        softSkillsTitle: "Soft Skills",
        tags: ["Critical Thinking", "Teamwork", "Communication", "Problem Solving", "Social Ethics"],
        careerTitle: "Career Interest",
        careerBody: "Strongly driven to pursue a career in **software engineering** — building **innovative digital solutions** that make a real difference for people and businesses.",
        careerCta: "Empowering local businesses to grow online",
    },

    education: {
        tag: "Academic Background",
        title: "My Education",
        subtitle: "Formal training in software engineering — building a strong foundation in modern web and mobile development technologies.",
        period: "2024 — 2026",
        active: "Active",
        schoolName: "IDN Boarding\nSchool",
        location: "Solo, Central Java · Indonesia",
        majorLabel: "Major",
        majorName: "Software Engineering (RPL)",
        subjectsTitle: "Relevant Subjects",
        subject1: "Web Development",
        subject1Chips: ["HTML", "CSS", "PHP", "JavaScript"],
        subject2: "Mobile App Development",
        subject2Chips: ["Flutter", "Dart"],
        subject3: "Frameworks & Tools",
        subject3Chips: ["Tailwind CSS", "Laravel", "Flutter"],
        achievementTitle: "Academic Achievements",
        achievementEmpty: "Still in Progress",
        achievementDesc: "Currently focused on sharpening skills and completing projects. **Achievements coming soon.**",
    },

    skills: {
        tag: "What I Can Do",
        title: "Skills & Expertise",
        subtitle: "A toolkit built through hands-on projects, real coursework, and relentless curiosity — always growing.",
        hardSkillsTitle: "Hard Skills",
        hardSkillsSub: "Core technical proficiency",
        toolsTitle: "Tools & Software",
        toolsSub: "Technologies I work with daily",
        softSkillsTitle: "Soft Skills",
        softSkillsSub: "How I work and think with others",
    },

    project1: {
        title: "QR Generator & Scanner",
        meta: "Flutter Development · 2024",
        descLabel: "Description",
        desc: "A Flutter-based mobile app that lets users scan various QR codes and generate custom QR codes from text or links.",
        goalTitle: "Project Goal",
        goalBody: "Simplify digital information exchange and data input automation through fast, accurate camera scanning.",
        roleTitle: "My Role",
        roleBody: "As **Main Developer**, I was responsible for the full development cycle.",
        resultTitle: "Results & Impact",
        results: [
            "Responsive and accurate scanning implementation.",
            "Clean and intuitive user interface (UI).",
            "Available on GitHub for community reference.",
        ],
        viewGitHub: "View on GitHub",
    },

    project2: {
        title: "UI E-commerce Implementation",
        meta: "Flutter Development · 2024",
        descLabel: "Description",
        desc: "Exploration of modern online shopping app interface design with Flutter.",
        goalTitle: "Project Goal",
        goalBody: "Create a seamless shopping experience through a clean interface and smooth transition animations.",
        roleTitle: "My Role",
        roleBody: "As **UI/UX Developer**, I designed and implemented all visual components.",
        resultTitle: "Results & Impact",
        results: [
            "Custom widget implementation for product grid.",
            "Smooth navigation between Cart, Profile, and Detail pages.",
            "Deep understanding of asset integration and theme management.",
        ],
        viewGitHub: "View on GitHub",
    },

    project3: {
        title: "Smart Attendance System",
        meta: "Flutter Development · 2024",
        descLabel: "Description",
        desc: "An attendance management app for institutions or schools.",
        goalTitle: "Goal / Motivation",
        goalBody: "Replace manual attendance systems and simplify automatic attendance data recap.",
        roleTitle: "Role & Contribution",
        roleBody: "As **Full Stack Developer**, I managed app state and attendance form integration.",
        resultTitle: "Results & Learning",
        results: [
            "Stable and reliable status management system.",
            "Improved understanding of mobile database management.",
            "Strict user data validation.",
        ],
        viewGitHub: "View on GitHub",
    },

    achievements: {
        title: "Achievements & Certifications",
        competitions: "Competitions",
        comingSoon: "Coming soon",
        comingSoonDesc: "Ready for the next challenge!",
        certifications: "Certifications",
        workshops: "Workshops",
        onlineCourses: "Online Courses",
        verify: "Verify",
        courseLink: "Course Link",
        docInProgress: "Documentation in progress",
    },

    challenges: {
        title: "Challenges & Learning",
        challengeTitle: "Biggest Challenge",
        challengeBody: "Becoming a Full Stack Developer",
        solutionTitle: "How I Overcome It",
        solutionBody: "Finding a mentor or learning from online resources",
        strategies: [
            { title: "Strategy 1", body: "Learn from trusted sources" },
            { title: "Strategy 2", body: "Build a project and share it on social media" },
            { title: "Strategy 3", body: "Gain more experience by building projects" },
        ],
        lessonsTitle: "Lessons Learned",
        lessons: [
            { title: "Lesson 1", body: "The importance of learning from trusted sources" },
            { title: "Lesson 2", body: "The importance of building a portfolio and sharing it on social media" },
            { title: "Lesson 3", body: "The importance of gaining experience through projects" },
        ],
    },

    careerGoal: {
        title: "Career Goals & Plans",
        visionTitle: "My Career Vision",
        visionBody: "To become a Full Stack Developer who contributes to creating technology solutions with social impact",
        shortTerm: "Short-term Goal",
        shortTermBody: "1-2 years - Master modern frameworks and land first job",
        midTerm: "Mid-term Goal",
        midTermBody: "3-5 years - Become a senior developer and lead a small team",
        longTerm: "Long-term Goal",
        longTermBody: "5+ years - Build my own startup or become a tech lead",
        skillsTitle: "Skills I Want to Develop",
        technicalSkills: "Technical Skills",
        professionalSkills: "Professional Skills",
        contributionTitle: "Contribution I Want to Give",
        contributionBody: "Creating technology products that help SMEs grow, sharing knowledge through mentoring, or contributing to the open-source community",
    },

    closing: {
        title: "Thank You! 🙏",
        subtitle: "I hope this presentation gives you a clear picture of my experience, skills, and career goals. I am excited to keep learning and contributing.",
        uniqueTitle: "What Makes Me Unique",
        unique1: "Never Give Up",
        unique2: "Results-Oriented",
        unique3: "Team Management",
        connectTitle: "Let's Connect!",
        email: "Email",
        linkedin: "LinkedIn",
        phone: "Phone",
        github: "Github",
        cta: "I'm open to discussion, collaboration, or new opportunities!",
        backToTop: "↑ Back to Top",
        footer: "© 2026 Jose Shabra Shatilla Rajjawani | Made with ❤️ using SvelteKit & Tailwind CSS",
    },
} as const;

export type ContentEn = typeof en;
