/**
 * Konten bahasa Indonesia.
 * Edit manual teks di sini untuk mengubah tampilan situs.
 */
export const id = {
    nav: {
        home: "Beranda",
        about: "Tentang",
        education: "Pendidikan",
        skills: "Keahlian",
        project1: "Proyek 1",
        project2: "Proyek 2",
        project3: "Proyek 3",
        achievements: "Prestasi",
        challenges: "Tantangan",
        career: "Karier",
        contact: "Kontak",
        portfolio: "Portfolio",
    },

    opening: {
        badge: "IDN Boarding School · Software Engineer",
        greeting: "Halo, saya",
        nameLine1: "Jose Shabra",
        nameLine2: "Shatilla Rajjawani",
        chip1: "Full Stack Developer",
        chip2: "Web Engineer",
        bio: "Membangun pengalaman web yang **bersih**, **responsif**, dan **modern** — mendorong UMKM tumbuh secara daring.",
        mission: "Portfolio ini memperkenalkan keterampilan, pengalaman, dan tujuan karier saya sebagai software engineer.",
        ctaBegin: "Mulai",
        ctaProjects: "Lihat Proyek",
        available: "Tersedia untuk Proyek",
        roleTop: "Full Stack",
        roleBot: "Developer",
        scrollHint: "Gulir untuk menjelajahi",
    },

    about: {
        tag: "Kenali saya",
        title: "Tentang Saya",
        subtitle: "Developer yang percaya pada pembuatan solusi bermakna melalui kode bersih dan pemikiran kreatif.",
        backgroundTitle: "Latar Belakang",
        backgroundBody: "Saya **Jose Shabra Shatilla Rajjawani**, siswa **IDN Boarding School, Solo**, jurusan **Rekayasa Perangkat Lunak (RPL)**. Saya sangat tertarik pada teknologi dan pengembangan perangkat lunak — selalu menjelajahi alat baru, mengerjakan proyek, dan mendorong batas kemampuan.",
        strengthsTitle: "Kekuatan Pribadi",
        strengths: [
            { label: "Adaptabilitas", desc: "Beradaptasi di lingkungan yang berubah cepat" },
            { label: "Manajemen Waktu", desc: "Menyelesaikan tugas tepat waktu" },
            { label: "Berorientasi Target", desc: "Fokus sampai tujuan tercapai" },
        ],
        softSkillsTitle: "Soft Skills",
        tags: ["Critical Thinking", "Teamwork", "Komunikasi", "Problem Solving", "Etika Sosial"],
        careerTitle: "Minat Karier",
        careerBody: "Berkomitmen mengejar karier di **rekayasa perangkat lunak** — membangun **solusi digital inovatif** yang berdampak bagi masyarakat dan bisnis.",
        careerCta: "Mendorong UMKM tumbuh secara daring",
    },

    education: {
        tag: "Latar Belakang Akademik",
        title: "Pendidikan Saya",
        subtitle: "Pendidikan formal di bidang rekayasa perangkat lunak — membangun fondasi kuat dalam teknologi pengembangan web dan mobile.",
        period: "2024 — 2026",
        active: "Aktif",
        schoolName: "IDN Boarding\nSchool",
        location: "Solo, Jawa Tengah · Indonesia",
        majorLabel: "Jurusan",
        majorName: "Rekayasa Perangkat Lunak (RPL)",
        subjectsTitle: "Mata Pelajaran Relevan",
        subject1: "Pengembangan Web",
        subject1Chips: ["HTML", "CSS", "PHP", "JavaScript"],
        subject2: "Pengembangan Aplikasi Mobile",
        subject2Chips: ["Flutter", "Dart"],
        subject3: "Framework & Alat",
        subject3Chips: ["Tailwind CSS", "Laravel", "Flutter"],
        achievementTitle: "Prestasi Akademik",
        achievementEmpty: "Masih dalam Proses",
        achievementDesc: "Saat ini fokus mengasah keterampilan dan menyelesaikan proyek. **Prestasi segera hadir.**",
    },

    skills: {
        tag: "Yang Bisa Saya Lakukan",
        title: "Keahlian & Kepakaran",
        subtitle: "Perangkat yang dibangun dari proyek nyata, pembelajaran formal, dan rasa ingin tahu — selalu berkembang.",
        hardSkillsTitle: "Hard Skills",
        hardSkillsSub: "Kemampuan teknis inti",
        toolsTitle: "Alat & Perangkat Lunak",
        toolsSub: "Teknologi yang sering saya gunakan",
        softSkillsTitle: "Soft Skills",
        softSkillsSub: "Cara saya bekerja dan berpikir dengan orang lain",
    },

    project1: {
        title: "QR Generator & Scanner",
        meta: "Pengembangan Flutter · 2024",
        descLabel: "Deskripsi",
        desc: "Aplikasi mobile berbasis Flutter untuk memindai berbagai jenis kode QR dan menghasilkan kode QR kustom dari teks atau link.",
        goalTitle: "Tujuan Proyek",
        goalBody: "Mempermudah pertukaran informasi digital dan otomasi input data melalui pemindaian kamera yang cepat dan akurat.",
        roleTitle: "Peran Saya",
        roleBody: "Sebagai **Main Developer**, saya bertanggung jawab atas seluruh siklus pengembangan.",
        resultTitle: "Hasil & Dampak",
        results: [
            "Implementasi pemindaian yang responsif dan akurat.",
            "Antarmuka pengguna (UI) yang bersih dan intuitif.",
            "Tersedia di GitHub untuk referensi komunitas.",
        ],
        viewGitHub: "Lihat di GitHub",
    },

    project2: {
        title: "UI E-commerce Implementation",
        meta: "Pengembangan Flutter · 2024",
        descLabel: "Deskripsi",
        desc: "Eksplorasi desain antarmuka aplikasi belanja online modern dengan Flutter.",
        goalTitle: "Tujuan Proyek",
        goalBody: "Menciptakan pengalaman belanja yang mulus melalui antarmuka bersih dan animasi transisi halus.",
        roleTitle: "Peran Saya",
        roleBody: "Sebagai **UI/UX Developer**, saya merancang dan mengimplementasikan seluruh komponen visual.",
        resultTitle: "Hasil & Dampak",
        results: [
            "Implementasi widget kustom untuk grid produk.",
            "Navigasi antar halaman yang mulus.",
            "Pemahaman mendalam tentang integrasi aset dan tema.",
        ],
        viewGitHub: "Lihat di GitHub",
    },

    project3: {
        title: "Smart Attendance System",
        meta: "Pengembangan Flutter · 2024",
        descLabel: "Deskripsi",
        desc: "Aplikasi manajemen kehadiran untuk efisiensi instansi atau sekolah.",
        goalTitle: "Tujuan / Motivasi",
        goalBody: "Menggantikan sistem absen manual, mempermudah rekapitulasi data kehadiran secara otomatis.",
        roleTitle: "Peran & Kontribusi",
        roleBody: "Sebagai **Full Stack Developer**, saya mengelola state aplikasi dan integrasi form presensi.",
        resultTitle: "Hasil & Pembelajaran",
        results: [
            "Sistem pengelolaan status yang stabil dan reliabel.",
            "Peningkatan pemahaman tentang basis data mobile.",
            "Validasi data pengguna yang ketat.",
        ],
        viewGitHub: "Lihat di GitHub",
    },

    achievements: {
        title: "Prestasi & Sertifikasi",
        competitions: "Kompetisi",
        comingSoon: "Segera hadir",
        comingSoonDesc: "Siap untuk tantangan berikutnya!",
        certifications: "Sertifikasi",
        workshops: "Workshop",
        onlineCourses: "Course Online",
        verify: "Verifikasi",
        courseLink: "Link Course",
        docInProgress: "Dokumentasi dalam pengerjaan",
    },

    challenges: {
        title: "Tantangan & Pembelajaran",
        challengeTitle: "Tantangan Terbesar",
        challengeBody: "Menjadi seorang Full Stack Developer",
        solutionTitle: "Cara Mengatasinya",
        solutionBody: "Mencari mentor atau belajar dari sumber-sumber online",
        strategies: [
            { title: "Strategi 1", body: "Belajar dari sumber-sumber yang terpercaya" },
            { title: "Strategi 2", body: "Membuat sebuah proyek dan membagikannya ke media sosial" },
            { title: "Strategi 3", body: "Perbanyak pengalaman dengan membuat proyek" },
        ],
        lessonsTitle: "Pelajaran yang Didapat",
        lessons: [
            { title: "Pelajaran 1", body: "Pentingnya belajar dari sumber-sumber yang terpercaya" },
            { title: "Pelajaran 2", body: "Pentingnya membuat portofolio dan membagikannya ke media sosial" },
            { title: "Pelajaran 3", body: "Pentingnya perbanyak pengalaman dengan membuat proyek" },
        ],
    },

    careerGoal: {
        title: "Tujuan & Rencana Karier",
        visionTitle: "Visi Karier Saya",
        visionBody: "Menjadi Full Stack Developer yang berkontribusi menciptakan solusi teknologi berdampak sosial",
        shortTerm: "Target Jangka Pendek",
        shortTermBody: "1-2 tahun - Menguasai framework modern dan mendapat pekerjaan pertama",
        midTerm: "Target Jangka Menengah",
        midTermBody: "3-5 tahun - Menjadi senior developer dan memimpin tim kecil",
        longTerm: "Target Jangka Panjang",
        longTermBody: "5+ tahun - Membangun startup sendiri atau menjadi tech lead",
        skillsTitle: "Skills yang Ingin Dikembangkan",
        technicalSkills: "Technical Skills",
        professionalSkills: "Professional Skills",
        contributionTitle: "Kontribusi yang Ingin Diberikan",
        contributionBody: "Menciptakan produk teknologi yang membantu UMKM berkembang, berbagi ilmu melalui mentoring, atau berkontribusi dalam open-source community",
    },

    closing: {
        title: "Terima Kasih! 🙏",
        subtitle: "Saya berharap presentasi ini memberikan gambaran jelas tentang pengalaman, kemampuan, dan tujuan karier saya. Saya sangat antusias untuk terus belajar dan berkontribusi.",
        uniqueTitle: "Yang Membuat Saya Unik",
        unique1: "Never Give Up",
        unique2: "Hasil-Oriented",
        unique3: "Team Management",
        connectTitle: "Mari Terhubung!",
        email: "Email",
        linkedin: "LinkedIn",
        phone: "Phone",
        github: "Github",
        cta: "Saya terbuka untuk diskusi, kolaborasi, atau peluang baru!",
        backToTop: "↑ Kembali ke Atas",
        footer: "© 2026 Jose Shabra Shatilla Rajjawani | Dibuat dengan ❤️ menggunakan SvelteKit & Tailwind CSS",
    },
} as const;

export type ContentId = typeof id;
